//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingRecordDetail
    {
        public int BookingRecordDetail_ID { get; set; }
        public Nullable<System.DateTime> CheckIn_Date { get; set; }
        public Nullable<System.DateTime> CheckOut_Date { get; set; }
        public Nullable<decimal> Purchase_Amount { get; set; }
        public Nullable<int> Room_ID { get; set; }
        public Nullable<int> Property_ID { get; set; }
        public Nullable<int> BookingRecord_ID { get; set; }
    
        public virtual BookingRecord BookingRecord { get; set; }
        public virtual Property Property { get; set; }
        public virtual Room Room { get; set; }
    }
}
