//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookingRecord()
        {
            this.BookingRecordDetails = new HashSet<BookingRecordDetail>();
        }
    
        public int BookingRecord_ID { get; set; }
        public string Client_email { get; set; }
        public string Client_FirstName { get; set; }
        public string Client_LastName { get; set; }
        public string Card_Number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingRecordDetail> BookingRecordDetails { get; set; }
    }
}
