//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public string Card_Number { get; set; }
        public string CVC_Code { get; set; }
        public Nullable<System.DateTime> Exp_date { get; set; }
        public Nullable<int> CardType_ID { get; set; }
        public string Client_email { get; set; }
    
        public virtual CardType CardType { get; set; }
        public virtual Client Client { get; set; }
    }
}
