//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.BookingRecordDetails = new HashSet<BookingRecordDetail>();
        }
    
        public int Room_ID { get; set; }
        public string Room_Name { get; set; }
        public string Room_Description { get; set; }
        public Nullable<int> Room_No_Occupants { get; set; }
        public Nullable<decimal> Room_Price { get; set; }
        public Nullable<int> Property_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingRecordDetail> BookingRecordDetails { get; set; }
        public virtual Property Property { get; set; }
    }
}
